// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/proto/triton/triton.proto

package triton

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelInferRequest struct {
	state            protoimpl.MessageState                `protogen:"open.v1"`
	ModelName        string                                `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion     string                                `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	Inputs           []*ModelInferRequest_InferInputTensor `protobuf:"bytes,5,rep,name=inputs,proto3" json:"inputs,omitempty"`
	RawInputContents [][]byte                              `protobuf:"bytes,8,rep,name=raw_input_contents,json=rawInputContents,proto3" json:"raw_input_contents,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModelInferRequest) Reset() {
	*x = ModelInferRequest{}
	mi := &file_api_proto_triton_triton_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInferRequest) ProtoMessage() {}

func (x *ModelInferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_triton_triton_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInferRequest.ProtoReflect.Descriptor instead.
func (*ModelInferRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_triton_triton_proto_rawDescGZIP(), []int{0}
}

func (x *ModelInferRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelInferRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ModelInferRequest) GetInputs() []*ModelInferRequest_InferInputTensor {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ModelInferRequest) GetRawInputContents() [][]byte {
	if x != nil {
		return x.RawInputContents
	}
	return nil
}

type ModelInferResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RawOutputContents [][]byte               `protobuf:"bytes,4,rep,name=raw_output_contents,json=rawOutputContents,proto3" json:"raw_output_contents,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ModelInferResponse) Reset() {
	*x = ModelInferResponse{}
	mi := &file_api_proto_triton_triton_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInferResponse) ProtoMessage() {}

func (x *ModelInferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_triton_triton_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInferResponse.ProtoReflect.Descriptor instead.
func (*ModelInferResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_triton_triton_proto_rawDescGZIP(), []int{1}
}

func (x *ModelInferResponse) GetRawOutputContents() [][]byte {
	if x != nil {
		return x.RawOutputContents
	}
	return nil
}

type ModelInferRequest_InferInputTensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Datatype      string                 `protobuf:"bytes,2,opt,name=datatype,proto3" json:"datatype,omitempty"`
	Shape         []int64                `protobuf:"varint,3,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInferRequest_InferInputTensor) Reset() {
	*x = ModelInferRequest_InferInputTensor{}
	mi := &file_api_proto_triton_triton_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInferRequest_InferInputTensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInferRequest_InferInputTensor) ProtoMessage() {}

func (x *ModelInferRequest_InferInputTensor) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_triton_triton_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInferRequest_InferInputTensor.ProtoReflect.Descriptor instead.
func (*ModelInferRequest_InferInputTensor) Descriptor() ([]byte, []int) {
	return file_api_proto_triton_triton_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ModelInferRequest_InferInputTensor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInferRequest_InferInputTensor) GetDatatype() string {
	if x != nil {
		return x.Datatype
	}
	return ""
}

func (x *ModelInferRequest_InferInputTensor) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

var File_api_proto_triton_triton_proto protoreflect.FileDescriptor

const file_api_proto_triton_triton_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/triton/triton.proto\x12\x06triton\"\xa3\x02\n" +
	"\x11ModelInferRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12B\n" +
	"\x06inputs\x18\x05 \x03(\v2*.triton.ModelInferRequest.InferInputTensorR\x06inputs\x12,\n" +
	"\x12raw_input_contents\x18\b \x03(\fR\x10rawInputContents\x1aX\n" +
	"\x10InferInputTensor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bdatatype\x18\x02 \x01(\tR\bdatatype\x12\x14\n" +
	"\x05shape\x18\x03 \x03(\x03R\x05shape\"D\n" +
	"\x12ModelInferResponse\x12.\n" +
	"\x13raw_output_contents\x18\x04 \x03(\fR\x11rawOutputContents2[\n" +
	"\x14GRPCInferenceService\x12C\n" +
	"\n" +
	"ModelInfer\x12\x19.triton.ModelInferRequest\x1a\x1a.triton.ModelInferResponseB;Z9github.com/platform/driver-delivery/pkg/api/triton;tritonb\x06proto3"

var (
	file_api_proto_triton_triton_proto_rawDescOnce sync.Once
	file_api_proto_triton_triton_proto_rawDescData []byte
)

func file_api_proto_triton_triton_proto_rawDescGZIP() []byte {
	file_api_proto_triton_triton_proto_rawDescOnce.Do(func() {
		file_api_proto_triton_triton_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_triton_triton_proto_rawDesc), len(file_api_proto_triton_triton_proto_rawDesc)))
	})
	return file_api_proto_triton_triton_proto_rawDescData
}

var file_api_proto_triton_triton_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_triton_triton_proto_goTypes = []any{
	(*ModelInferRequest)(nil),                  // 0: triton.ModelInferRequest
	(*ModelInferResponse)(nil),                 // 1: triton.ModelInferResponse
	(*ModelInferRequest_InferInputTensor)(nil), // 2: triton.ModelInferRequest.InferInputTensor
}
var file_api_proto_triton_triton_proto_depIdxs = []int32{
	2, // 0: triton.ModelInferRequest.inputs:type_name -> triton.ModelInferRequest.InferInputTensor
	0, // 1: triton.GRPCInferenceService.ModelInfer:input_type -> triton.ModelInferRequest
	1, // 2: triton.GRPCInferenceService.ModelInfer:output_type -> triton.ModelInferResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_triton_triton_proto_init() }
func file_api_proto_triton_triton_proto_init() {
	if File_api_proto_triton_triton_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_triton_triton_proto_rawDesc), len(file_api_proto_triton_triton_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_triton_triton_proto_goTypes,
		DependencyIndexes: file_api_proto_triton_triton_proto_depIdxs,
		MessageInfos:      file_api_proto_triton_triton_proto_msgTypes,
	}.Build()
	File_api_proto_triton_triton_proto = out.File
	file_api_proto_triton_triton_proto_goTypes = nil
	file_api_proto_triton_triton_proto_depIdxs = nil
}
