// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: telemetry/v1/telemetry.proto

package telemetryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocationIngestionService_ClientStreamPositions_FullMethodName = "/telemetry.v1.LocationIngestionService/ClientStreamPositions"
)

// LocationIngestionServiceClient is the client API for LocationIngestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationIngestionServiceClient interface {
	ClientStreamPositions(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestionRequest, IngestionResponse], error)
}

type locationIngestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationIngestionServiceClient(cc grpc.ClientConnInterface) LocationIngestionServiceClient {
	return &locationIngestionServiceClient{cc}
}

func (c *locationIngestionServiceClient) ClientStreamPositions(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestionRequest, IngestionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocationIngestionService_ServiceDesc.Streams[0], LocationIngestionService_ClientStreamPositions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestionRequest, IngestionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocationIngestionService_ClientStreamPositionsClient = grpc.ClientStreamingClient[IngestionRequest, IngestionResponse]

// LocationIngestionServiceServer is the server API for LocationIngestionService service.
// All implementations must embed UnimplementedLocationIngestionServiceServer
// for forward compatibility.
type LocationIngestionServiceServer interface {
	ClientStreamPositions(grpc.ClientStreamingServer[IngestionRequest, IngestionResponse]) error
	mustEmbedUnimplementedLocationIngestionServiceServer()
}

// UnimplementedLocationIngestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocationIngestionServiceServer struct{}

func (UnimplementedLocationIngestionServiceServer) ClientStreamPositions(grpc.ClientStreamingServer[IngestionRequest, IngestionResponse]) error {
	return status.Error(codes.Unimplemented, "method ClientStreamPositions not implemented")
}
func (UnimplementedLocationIngestionServiceServer) mustEmbedUnimplementedLocationIngestionServiceServer() {
}
func (UnimplementedLocationIngestionServiceServer) testEmbeddedByValue() {}

// UnsafeLocationIngestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationIngestionServiceServer will
// result in compilation errors.
type UnsafeLocationIngestionServiceServer interface {
	mustEmbedUnimplementedLocationIngestionServiceServer()
}

func RegisterLocationIngestionServiceServer(s grpc.ServiceRegistrar, srv LocationIngestionServiceServer) {
	// If the following call panics, it indicates UnimplementedLocationIngestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocationIngestionService_ServiceDesc, srv)
}

func _LocationIngestionService_ClientStreamPositions_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocationIngestionServiceServer).ClientStreamPositions(&grpc.GenericServerStream[IngestionRequest, IngestionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocationIngestionService_ClientStreamPositionsServer = grpc.ClientStreamingServer[IngestionRequest, IngestionResponse]

// LocationIngestionService_ServiceDesc is the grpc.ServiceDesc for LocationIngestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationIngestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.v1.LocationIngestionService",
	HandlerType: (*LocationIngestionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStreamPositions",
			Handler:       _LocationIngestionService_ClientStreamPositions_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "telemetry/v1/telemetry.proto",
}
