// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: telemetry/v1/telemetry.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	CityPrefix    string                 `protobuf:"bytes,2,opt,name=city_prefix,json=cityPrefix,proto3" json:"city_prefix,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Bearing       float32                `protobuf:"fixed32,5,opt,name=bearing,proto3" json:"bearing,omitempty"`
	SpeedKms      float32                `protobuf:"fixed32,6,opt,name=speed_kms,json=speedKms,proto3" json:"speed_kms,omitempty"`
	TimestampUtc  int64                  `protobuf:"varint,7,opt,name=timestamp_utc,json=timestampUtc,proto3" json:"timestamp_utc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionRequest) Reset() {
	*x = IngestionRequest{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionRequest) ProtoMessage() {}

func (x *IngestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionRequest.ProtoReflect.Descriptor instead.
func (*IngestionRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *IngestionRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *IngestionRequest) GetCityPrefix() string {
	if x != nil {
		return x.CityPrefix
	}
	return ""
}

func (x *IngestionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *IngestionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *IngestionRequest) GetBearing() float32 {
	if x != nil {
		return x.Bearing
	}
	return 0
}

func (x *IngestionRequest) GetSpeedKms() float32 {
	if x != nil {
		return x.SpeedKms
	}
	return 0
}

func (x *IngestionRequest) GetTimestampUtc() int64 {
	if x != nil {
		return x.TimestampUtc
	}
	return 0
}

type IngestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecordedAt    int64                  `protobuf:"varint,2,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionResponse) Reset() {
	*x = IngestionResponse{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionResponse) ProtoMessage() {}

func (x *IngestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionResponse.ProtoReflect.Descriptor instead.
func (*IngestionResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *IngestionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestionResponse) GetRecordedAt() int64 {
	if x != nil {
		return x.RecordedAt
	}
	return 0
}

var File_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1ctelemetry/v1/telemetry.proto\x12\ftelemetry.v1\"\xe6\x01\n" +
	"\x10IngestionRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vcity_prefix\x18\x02 \x01(\tR\n" +
	"cityPrefix\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x18\n" +
	"\abearing\x18\x05 \x01(\x02R\abearing\x12\x1b\n" +
	"\tspeed_kms\x18\x06 \x01(\x02R\bspeedKms\x12#\n" +
	"\rtimestamp_utc\x18\a \x01(\x03R\ftimestampUtc\"N\n" +
	"\x11IngestionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vrecorded_at\x18\x02 \x01(\x03R\n" +
	"recordedAt2v\n" +
	"\x18LocationIngestionService\x12Z\n" +
	"\x15ClientStreamPositions\x12\x1e.telemetry.v1.IngestionRequest\x1a\x1f.telemetry.v1.IngestionResponse(\x01BFZDgithub.com/platform/driver-delivery/pkg/api/telemetry/v1;telemetryv1b\x06proto3"

var (
	file_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_telemetry_v1_telemetry_proto_rawDescData
}

var file_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telemetry_v1_telemetry_proto_goTypes = []any{
	(*IngestionRequest)(nil),  // 0: telemetry.v1.IngestionRequest
	(*IngestionResponse)(nil), // 1: telemetry.v1.IngestionResponse
}
var file_telemetry_v1_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.v1.LocationIngestionService.ClientStreamPositions:input_type -> telemetry.v1.IngestionRequest
	1, // 1: telemetry.v1.LocationIngestionService.ClientStreamPositions:output_type -> telemetry.v1.IngestionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_telemetry_v1_telemetry_proto_init() }
func file_telemetry_v1_telemetry_proto_init() {
	if File_telemetry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_v1_telemetry_proto = out.File
	file_telemetry_v1_telemetry_proto_goTypes = nil
	file_telemetry_v1_telemetry_proto_depIdxs = nil
}
