// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/proto/v1/stream_framing.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameType int32

const (
	FrameType_FRAME_TYPE_UNSPECIFIED FrameType = 0
	FrameType_FRAME_TYPE_ASSIGNMENT  FrameType = 1
	FrameType_FRAME_TYPE_TELEMETRY   FrameType = 2
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0: "FRAME_TYPE_UNSPECIFIED",
		1: "FRAME_TYPE_ASSIGNMENT",
		2: "FRAME_TYPE_TELEMETRY",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_UNSPECIFIED": 0,
		"FRAME_TYPE_ASSIGNMENT":  1,
		"FRAME_TYPE_TELEMETRY":   2,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_stream_framing_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_stream_framing_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_stream_framing_proto_rawDescGZIP(), []int{0}
}

type AssignmentFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	CityPrefix    string                 `protobuf:"bytes,3,opt,name=city_prefix,json=cityPrefix,proto3" json:"city_prefix,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignmentFrame) Reset() {
	*x = AssignmentFrame{}
	mi := &file_api_proto_v1_stream_framing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentFrame) ProtoMessage() {}

func (x *AssignmentFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_stream_framing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentFrame.ProtoReflect.Descriptor instead.
func (*AssignmentFrame) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_stream_framing_proto_rawDescGZIP(), []int{0}
}

func (x *AssignmentFrame) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AssignmentFrame) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *AssignmentFrame) GetCityPrefix() string {
	if x != nil {
		return x.CityPrefix
	}
	return ""
}

func (x *AssignmentFrame) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TelemetryFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Bearing       float64                `protobuf:"fixed64,5,opt,name=bearing,proto3" json:"bearing,omitempty"`
	SpeedKms      float64                `protobuf:"fixed64,6,opt,name=speed_kms,json=speedKms,proto3" json:"speed_kms,omitempty"`
	TimestampUtc  int64                  `protobuf:"varint,7,opt,name=timestamp_utc,json=timestampUtc,proto3" json:"timestamp_utc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryFrame) Reset() {
	*x = TelemetryFrame{}
	mi := &file_api_proto_v1_stream_framing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryFrame) ProtoMessage() {}

func (x *TelemetryFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_stream_framing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryFrame.ProtoReflect.Descriptor instead.
func (*TelemetryFrame) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_stream_framing_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryFrame) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *TelemetryFrame) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *TelemetryFrame) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TelemetryFrame) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TelemetryFrame) GetBearing() float64 {
	if x != nil {
		return x.Bearing
	}
	return 0
}

func (x *TelemetryFrame) GetSpeedKms() float64 {
	if x != nil {
		return x.SpeedKms
	}
	return 0
}

func (x *TelemetryFrame) GetTimestampUtc() int64 {
	if x != nil {
		return x.TimestampUtc
	}
	return 0
}

type WebSocketBinaryEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FrameType              `protobuf:"varint,1,opt,name=type,proto3,enum=api.proto.v1.FrameType" json:"type,omitempty"`
	Assignment    *AssignmentFrame       `protobuf:"bytes,2,opt,name=assignment,proto3" json:"assignment,omitempty"`
	Telemetry     *TelemetryFrame        `protobuf:"bytes,3,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketBinaryEnvelope) Reset() {
	*x = WebSocketBinaryEnvelope{}
	mi := &file_api_proto_v1_stream_framing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketBinaryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketBinaryEnvelope) ProtoMessage() {}

func (x *WebSocketBinaryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_stream_framing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketBinaryEnvelope.ProtoReflect.Descriptor instead.
func (*WebSocketBinaryEnvelope) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_stream_framing_proto_rawDescGZIP(), []int{2}
}

func (x *WebSocketBinaryEnvelope) GetType() FrameType {
	if x != nil {
		return x.Type
	}
	return FrameType_FRAME_TYPE_UNSPECIFIED
}

func (x *WebSocketBinaryEnvelope) GetAssignment() *AssignmentFrame {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *WebSocketBinaryEnvelope) GetTelemetry() *TelemetryFrame {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

var File_api_proto_v1_stream_framing_proto protoreflect.FileDescriptor

const file_api_proto_v1_stream_framing_proto_rawDesc = "" +
	"\n" +
	"!api/proto/v1/stream_framing.proto\x12\fapi.proto.v1\"\x82\x01\n" +
	"\x0fAssignmentFrame\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vcity_prefix\x18\x03 \x01(\tR\n" +
	"cityPrefix\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xde\x01\n" +
	"\x0eTelemetryFrame\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x18\n" +
	"\abearing\x18\x05 \x01(\x01R\abearing\x12\x1b\n" +
	"\tspeed_kms\x18\x06 \x01(\x01R\bspeedKms\x12#\n" +
	"\rtimestamp_utc\x18\a \x01(\x03R\ftimestampUtc\"\xc1\x01\n" +
	"\x17WebSocketBinaryEnvelope\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.api.proto.v1.FrameTypeR\x04type\x12=\n" +
	"\n" +
	"assignment\x18\x02 \x01(\v2\x1d.api.proto.v1.AssignmentFrameR\n" +
	"assignment\x12:\n" +
	"\ttelemetry\x18\x03 \x01(\v2\x1c.api.proto.v1.TelemetryFrameR\ttelemetry*\\\n" +
	"\tFrameType\x12\x1a\n" +
	"\x16FRAME_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FRAME_TYPE_ASSIGNMENT\x10\x01\x12\x18\n" +
	"\x14FRAME_TYPE_TELEMETRY\x10\x02B6Z4github.com/platform/driver-delivery/pkg/api/v1;apiv1b\x06proto3"

var (
	file_api_proto_v1_stream_framing_proto_rawDescOnce sync.Once
	file_api_proto_v1_stream_framing_proto_rawDescData []byte
)

func file_api_proto_v1_stream_framing_proto_rawDescGZIP() []byte {
	file_api_proto_v1_stream_framing_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_stream_framing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_stream_framing_proto_rawDesc), len(file_api_proto_v1_stream_framing_proto_rawDesc)))
	})
	return file_api_proto_v1_stream_framing_proto_rawDescData
}

var file_api_proto_v1_stream_framing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_stream_framing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_v1_stream_framing_proto_goTypes = []any{
	(FrameType)(0),                  // 0: api.proto.v1.FrameType
	(*AssignmentFrame)(nil),         // 1: api.proto.v1.AssignmentFrame
	(*TelemetryFrame)(nil),          // 2: api.proto.v1.TelemetryFrame
	(*WebSocketBinaryEnvelope)(nil), // 3: api.proto.v1.WebSocketBinaryEnvelope
}
var file_api_proto_v1_stream_framing_proto_depIdxs = []int32{
	0, // 0: api.proto.v1.WebSocketBinaryEnvelope.type:type_name -> api.proto.v1.FrameType
	1, // 1: api.proto.v1.WebSocketBinaryEnvelope.assignment:type_name -> api.proto.v1.AssignmentFrame
	2, // 2: api.proto.v1.WebSocketBinaryEnvelope.telemetry:type_name -> api.proto.v1.TelemetryFrame
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_v1_stream_framing_proto_init() }
func file_api_proto_v1_stream_framing_proto_init() {
	if File_api_proto_v1_stream_framing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_stream_framing_proto_rawDesc), len(file_api_proto_v1_stream_framing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_stream_framing_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_stream_framing_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_stream_framing_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_stream_framing_proto_msgTypes,
	}.Build()
	File_api_proto_v1_stream_framing_proto = out.File
	file_api_proto_v1_stream_framing_proto_goTypes = nil
	file_api_proto_v1_stream_framing_proto_depIdxs = nil
}
