DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'driver_duty_state') THEN
        CREATE TYPE driver_duty_state AS ENUM ('OFFLINE', 'ONLINE', 'OFFER_PENDING', 'EN_ROUTE', 'ARRIVED', 'DELIVERING', 'EMERGENCY');
    END IF;
END$$;

ALTER TABLE drivers 
ADD COLUMN IF NOT EXISTS duty_state driver_duty_state DEFAULT 'OFFLINE',
ADD COLUMN IF NOT EXISTS last_lat DECIMAL(9,6),
ADD COLUMN IF NOT EXISTS last_lng DECIMAL(9,6),
ADD COLUMN IF NOT EXISTS rating DECIMAL(3,2) DEFAULT 5.0;
