ALTER TABLE operational_geofences
ADD COLUMN policy_type VARCHAR(50) DEFAULT 'ACTIVE_DISPATCH' NOT NULL,
ADD COLUMN surge_multiplier NUMERIC(3, 2) DEFAULT 1.00 NOT NULL,
ADD COLUMN allowed_transmissions VARCHAR(50) DEFAULT 'ALL' NOT NULL,
ADD COLUMN activation_start TIMESTAMP WITH TIME ZONE,
ADD COLUMN activation_end TIMESTAMP WITH TIME ZONE,
ADD COLUMN notes TEXT;
