ALTER TABLE orders_gps_trail 
ADD COLUMN speed DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN heading DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN battery INT NOT NULL DEFAULT 100,
ADD COLUMN network_type VARCHAR(15) NOT NULL DEFAULT 'unknown';
