apiVersion: v1
kind: Service
metadata:
  name: {{ include "drivers-for-u.name" . }}-analytics-svc
  labels:
    app: analytics
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.analytics.port }}
      targetPort: http
      name: http
  selector:
    app: analytics
