apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drivers-for-u.name" . }}-expiry
  labels:
    app: expiry
spec:
  replicas: {{ .Values.expiry.replicaCount }}
  selector:
    matchLabels:
      app: expiry
  template:
    metadata:
      labels:
        app: expiry
    spec:
      containers:
        - name: expiry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/entrypoint"]
          env:
            - name: TARGET_SERVICE
              value: "expiry"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "drivers-for-u.name" . }}-db-credentials
                  key: database-url
            - name: KAFKA_BROKERS
              value: {{ .Values.global.env.kafkaBrokers | quote }}
            - name: REDIS_CLUSTER_NODES
              value: {{ .Values.global.env.redisClusterNodes | quote }}
            - name: CITY_PREFIX
              value: {{ .Values.global.region | quote }}
          resources:
            {{- toYaml .Values.expiry.resources | nindent 12 }}
