apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drivers-for-u.name" . }}-pruner
  labels:
    app: pruner
spec:
  replicas: {{ .Values.pruner.replicaCount }}
  selector:
    matchLabels:
      app: pruner
  template:
    metadata:
      labels:
        app: pruner
    spec:
      containers:
        - name: pruner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/entrypoint"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "drivers-for-u.name" . }}-db-credentials
                  key: database-url
            - name: REDIS_CLUSTER_NODES
              value: {{ .Values.global.env.redisClusterNodes | quote }}
          resources:
            {{- toYaml .Values.pruner.resources | nindent 12 }}
