apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drivers-for-u.name" . }}-db-credentials
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  database-url: {{ .Values.global.env.databaseUrl | quote }}
