apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drivers-for-u.name" . }}-surge
  labels:
    app: surge
spec:
  replicas: {{ .Values.surge.replicaCount }}
  selector:
    matchLabels:
      app: surge
  template:
    metadata:
      labels:
        app: surge
    spec:
      containers:
        - name: surge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/entrypoint"]
          env:
            - name: KAFKA_BROKERS
              value: {{ .Values.networkPolicy.env.kafkaBrokers | quote }}
            - name: REDIS_CLUSTER_NODES
              value: {{ .Values.networkPolicy.env.redisClusterNodes | quote }}
            - name: SURGE_CITY_PREFIX
              value: {{ .Values.global.region | quote }}
            - name: SURGE_TRACKED_CELLS
              value: {{ .Values.surge.trackedCells | quote }}
          resources:
            {{- toYaml .Values.surge.resources | nindent 12 }}
