apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vahnly.name" . }}-expiry
  labels:
    app: expiry
spec:
  replicas: {{ .Values.expiry.replicaCount }}
  selector:
    matchLabels:
      app: expiry
  template:
    metadata:
      labels:
        app: expiry
    spec:
      containers:
        - name: expiry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- include "vahnly.securityContext" . | nindent 12 }}
          command: ["/entrypoint"]
          env:
            - name: TARGET_SERVICE
              value: "expiry"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "vahnly.name" . }}-db-credentials
                  key: database-url
            - name: KAFKA_BROKERS
              value: {{ .Values.global.env.kafkaBrokers | quote }}
            - name: REDIS_CLUSTER_NODES
              value: {{ .Values.global.env.redisClusterNodes | quote }}
            {{- include "vahnly.redisAuthEnv" . | nindent 12 }}
            - name: CITY_PREFIX
              value: {{ .Values.global.region | quote }}
            {{- include "vahnly.kafkaSecurityEnv" . | nindent 12 }}
          ports:
            - containerPort: 8080
              name: health
          livenessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ready
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.expiry.resources | nindent 12 }}
