apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vahnly.name" . }}-notification
  labels:
    app: notification
spec:
  replicas: {{ .Values.notification.replicaCount }}
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- include "vahnly.securityContext" . | nindent 12 }}
          command: ["/entrypoint"]
          env:
            - name: TARGET_SERVICE
              value: "notification"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "vahnly.name" . }}-db-credentials
                  key: database-url
          ports:
            - containerPort: 8080
              name: health
          livenessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ready
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.notification.resources | nindent 12 }}
