apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vahnly.name" . }}-pruner
  labels:
    app: pruner
spec:
  replicas: {{ .Values.pruner.replicaCount }}
  selector:
    matchLabels:
      app: pruner
  template:
    metadata:
      labels:
        app: pruner
    spec:
      containers:
        - name: pruner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- include "vahnly.securityContext" . | nindent 12 }}
          command: ["/entrypoint"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "vahnly.name" . }}-db-credentials
                  key: database-url
            - name: REDIS_CLUSTER_NODES
              value: {{ .Values.global.env.redisClusterNodes | quote }}
            {{- include "vahnly.redisAuthEnv" . | nindent 12 }}
          ports:
            - containerPort: 8080
              name: health
          livenessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ready
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.pruner.resources | nindent 12 }}
