apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drivers-for-u.name" . }}-rebalancer
  labels:
    app: rebalancer
spec:
  replicas: {{ .Values.rebalancer.replicaCount }}
  selector:
    matchLabels:
      app: rebalancer
  template:
    metadata:
      labels:
        app: rebalancer
    spec:
      containers:
        - name: rebalancer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- include "drivers-for-u.securityContext" . | nindent 12 }}
          command: ["/entrypoint"]
          env:
            - name: TARGET_SERVICE
              value: "rebalancer"
            - name: REDIS_CLUSTER_NODES
              value: {{ .Values.global.env.redisClusterNodes | quote }}
            {{- include "drivers-for-u.redisAuthEnv" . | nindent 12 }}
            - name: CITY_PREFIX
              value: {{ .Values.global.region | quote }}
            - name: REBALANCER_HTTP_ADDR
              value: {{ .Values.rebalancer.httpAddr | quote }}
          ports:
            - containerPort: 8090
              name: http
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.rebalancer.resources | nindent 12 }}
